openapi: "3.0.3"
info:
  version: 1.0.0
  title: Curious Outcomes public API
  description: These are the public API endpoints for the Curious Outcomes system.
servers:
  - url: http://to.be.defined/v1

paths:

  # Courses
  /courses/{id}:
    $ref: "./src/courses/find-one/find-one.path.yaml"
