openapi: "3.0.3"
info:
  version: 1.0.0
  title: Curious Outcomes API
  description: Access to the Curious Outcomes API
servers:
  - url: http://to.be.defined/v1

paths:
  /system/events/transform:
    $ref: "./apps/system/src/modules/events/path-events-transform.yaml"
