version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "curious-outcomes"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-a80yn0d1bj2e"
s3_prefix = "curious-outcomes"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
