type: object
required:
  - id
  - type
  - payload
properties:
  eventId:
    type: string
  type:
    type: string
  data:
    type: object
    required:
      - id
    properties:
      id:
        type: string
